### PR TITLE
fix serializing

### PR DESCRIPTION
**Pull request by McFlurriez**

### CODE REVIEW

**Comment by McFlurriez** [comment]
@sihil could you accept and merge this? This bug causes a double serialize. Thanks!

**Comment by mchv** [comment]
👍  we need to release a new version

**Comment by McFlurriez** [comment]
@mchv Sounds good, anything you'd like me to do? How can we get this out?

**Comment by Reettaphant** [comment]
@McFlurriez I've added the npm package to guardian organisation now so anyone in the guardian organisation will be able to release a new version. The package on npm has a new name now: doing this required changing the package name from thrift-serializer to @guardian/thrift-serializer.

**Pull request merged**
